import logging
import json
import hashlib
import base64

import jwt
from aiohttp import web
from cryptography.hazmat.primitives import serialization

from .app_util import *
from . import util
from . import crypto
from . import cbrrr

logger = logging.getLogger(__name__)

routes = web.RouteTableDef()


def jwk_thumbprint(jwk_dict: dict) -> str:
	"""Compute JWK thumbprint per RFC 7638"""
	required = {k: jwk_dict[k] for k in sorted(["crv", "kty", "x", "y"]) if k in jwk_dict}
	canon = json.dumps(required, separators=(',', ':'), sort_keys=True)
	digest = hashlib.sha256(canon.encode()).digest()
	return base64.urlsafe_b64encode(digest).rstrip(b'=').decode()


def verify_symmetric_token(
	request: web.Request, token: str, expected_scope: str
) -> dict:
	db = get_db(request)
	try:
		payload: dict = jwt.decode(
			jwt=token,
			key=db.config["jwt_access_secret"],
			algorithms=["HS256"],
			audience=db.config["pds_did"],
			options={
				"require": ["exp", "iat", "scope", "jti", "sub"],
				"verify_exp": True,
				"verify_iat": True,
				"strict_aud": True,  # may be unnecessary
			},
		)
	except jwt.exceptions.ExpiredSignatureError:
		# https://github.com/bluesky-social/atproto/discussions/3319
		# we need to signal this error in this specific format so the reference
		# client implementation will know what to do
		raise util.atproto_json_http_error(
			web.HTTPBadRequest, "ExpiredToken", "bad exp"
		)
	except jwt.exceptions.PyJWTError:
		raise web.HTTPUnauthorized(text="invalid jwt")

	revoked = db.con.execute(
		"SELECT COUNT(*) FROM revoked_token WHERE did=? AND jti=?",
		(payload["sub"], payload["jti"]),
	).get

	if revoked:
		raise web.HTTPUnauthorized(text="revoked token")

	# if we reached this far, the payload must've been signed by us
	if payload.get("scope") != expected_scope:
		raise web.HTTPUnauthorized(text="invalid jwt scope")

	if not payload.get("sub", "").startswith("did:"):
		raise web.HTTPUnauthorized(text="invalid jwt: invalid subject")

	return payload


def authenticated(handler):
	"""
	There are three types of auth:
	 - bearer token signed by symmetric secret (generated by us during the password login flow)
	 - "service" bearer token signed by (asymmetric) repo signing key, scoped to a specific lxm
	 - whatever I do for oauth (TODO)
	"""

	async def authentication_handler(request: web.Request, *args, **kwargs):
		# extract the auth token
		auth = request.headers.get("Authorization")
		if auth is None:
			raise web.HTTPUnauthorized(
				text="authentication required (this may be a bug, I'm erring on the side of caution for now)"
			)
		if not auth.startswith("Bearer "):
			raise web.HTTPUnauthorized(text="invalid auth type")
		token = auth.removeprefix("Bearer ")

		# validate it TODO: this needs rigorous testing, I'm not 100% sure I'm
		# verifying all the things that need verifying
		db = get_db(request)

		unverified = jwt.api_jwt.decode_complete(
			token, options={"verify_signature": False}
		)
		# logger.info(unverified)

		cfg = db.config

		if unverified["header"]["alg"] == "HS256":  # symmetric secret
			request["authed_did"] = verify_symmetric_token(
				request, token, "com.atproto.access"
			)["sub"]
		elif unverified["payload"].get("iss") == cfg["auth_pfx"]:  # OAuth access token
			# Verify with server AS public key
			privkey_pem = cfg["server_as_privkey"]
			privkey = serialization.load_pem_private_key(privkey_pem.encode(), password=None)
			pubkey = privkey.public_key()

			try:
				payload = jwt.decode(
					jwt=token,
					key=pubkey,
					algorithms=["ES256"],
					issuer=cfg["auth_pfx"],
					audience=cfg["pds_pfx"],
					options={
						"require": ["exp", "iat", "sub", "cnf", "jti"],
						"verify_exp": True,
						"verify_iat": True,
						"strict_aud": True,
					},
				)
			except jwt.exceptions.PyJWTError as e:
				raise web.HTTPUnauthorized(text=f"invalid oauth token: {e}")

			# Verify DPoP binding if present
			if "cnf" in payload and "jkt" in payload["cnf"]:
				dpop = request.headers.get("dpop")
				if not dpop:
					raise web.HTTPUnauthorized(text="dpop required for this token")

				try:
					unverified_dpop = jwt.api_jwt.decode_complete(
						dpop, options={"verify_signature": False}
					)
					jwk_data = unverified_dpop["header"]["jwk"]
					jwk = jwt.PyJWK.from_dict(jwk_data)
					jwt.decode(dpop, key=jwk)  # verify signature

					# Verify thumbprint matches
					current_jkt = jwk_thumbprint(jwk_data)
					if current_jkt != payload["cnf"]["jkt"]:
						raise web.HTTPUnauthorized(text="dpop jkt mismatch")
				except jwt.exceptions.PyJWTError:
					raise web.HTTPUnauthorized(text="invalid dpop proof")

			request["authed_did"] = payload["sub"]
		else:  # asymmetric service auth (scoped to a specific lxm)
			did: str = unverified["payload"]["iss"]
			if not did.startswith("did:"):
				raise web.HTTPUnauthorized(text="invalid jwt: invalid issuer")
			signing_key_pem = db.signing_key_pem_by_did(did)
			if signing_key_pem is None:
				raise web.HTTPUnauthorized(text="invalid jwt: unknown issuer")
			alg = crypto.jwt_signature_alg_for_pem(signing_key_pem)
			verifying_key = crypto.privkey_from_pem(
				signing_key_pem
			).public_key()
			try:
				payload = jwt.decode(
					jwt=token,
					key=verifying_key,
					algorithms=[alg],
					audience=db.config["pds_did"],
					options={
						"require": ["exp", "iat", "lxm", "jti", "iss"],
						"verify_exp": True,
						"verify_iat": True,
						"strict_aud": True,  # may be unnecessary
					},
				)
			except jwt.exceptions.PyJWTError:
				raise web.HTTPUnauthorized(text="invalid jwt")

			revoked = db.con.execute(
				"SELECT COUNT(*) FROM revoked_token WHERE did=? AND jti=?",
				(payload["iss"], payload["jti"]),
			).get

			if revoked:
				raise web.HTTPUnauthorized(text="revoked token")

			request_lxm = request.path.rpartition("/")[2].partition("?")[0]
			if request_lxm != payload.get("lxm"):
				raise web.HTTPUnauthorized(text="invalid jwt: bad lxm")

			# everything checks out
			request["authed_did"] = did

		return await handler(request, *args, **kwargs)

	return authentication_handler
